CREATE TABLE "user" (
                        user_name           VARCHAR(255) PRIMARY KEY,
                        first_name          VARCHAR(255) NOT NULL,
                        last_name           VARCHAR(255) NOT NULL,
                        dob                 DATE NOT NULL,
                        email               VARCHAR(255) UNIQUE NOT NULL,
                        password            VARCHAR(255) NOT NULL,
                        profile_picture_url VARCHAR(255)
);

CREATE TABLE income_expense (
                                id                SERIAL PRIMARY KEY,
                                user_name         VARCHAR(255) NOT NULL,
                                type              VARCHAR(255),
                                description       VARCHAR(255),
                                amount            NUMERIC(38, 2) NOT NULL CHECK (amount > 0),
                                transaction_date  VARCHAR(255) DEFAULT CURRENT_DATE NOT NULL,
                                create_at         VARCHAR(255) DEFAULT CURRENT_TIMESTAMP,
                                updated_at        VARCHAR(255) DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT fk_user FOREIGN KEY (user_name) REFERENCES "user"(user_name) ON DELETE CASCADE
);

CREATE TABLE "AuditLog" (
                            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            action     VARCHAR(255) CHECK (action IN (
                                                                      'CREATE', 'UPDATE', 'DELETE', 'READ',
                                                                      'LOGIN', 'LOGOUT', 'BACKUP', 'RESTORE',
                                                                      'PASSWORD_UPDATE', 'PASSWORD_RESET'
                                )),
                            category   VARCHAR(255) CHECK (category IN (
                                                                        'TRANSACTION', 'USER_PROFILE', 'AUTH', 'BACKUP', 'SETTINGS'
                                )),
                            details    VARCHAR(255),
                            "targetId" VARCHAR(255),
                            timestamp  TIMESTAMP(6),
                            "userName" VARCHAR(255)
);